-- MySQL Script generated by MySQL Workbench
-- Sun Mar  1 02:08:15 2020
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `openpay` ;

-- -----------------------------------------------------
-- Schema sakila
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `openpay` ;
SHOW WARNINGS;
USE `openpay` ;

-- -----------------------------------------------------
-- Table `CREDITO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CREDITO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CREDITO` (
  `idCREDITO` INT NOT NULL,
  `TIPO_CREDITO` VARCHAR(45) NOT NULL,
  `LIMITE_CREDITO` DOUBLE NULL,
  `CREDITO` DOUBLE NULL,
  `FECHA_INI` DATETIME NULL,
  `FECHA_FIN` DATETIME NULL,
  `CUENTA_idCUENTA` INT NOT NULL,
  `CUENTA_USUARIO_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`idCREDITO`, `CUENTA_idCUENTA`, `CUENTA_USUARIO_USUARIO_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `CUENTA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CUENTA` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `CUENTA` (
  `idCUENTA` INT NOT NULL,
  `PRODUCTO` VARCHAR(45) NOT NULL,
  `CUENTA_CLABE` VARCHAR(45) NOT NULL,
  `USUARIO_USUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`idCUENTA`, `USUARIO_USUARIO_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `CUENTA_CKABE_INDEX` ON `CUENTA` (`CUENTA_CLABE` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `USUARIO` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `USUARIO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `APELLIDO_PATERNO` VARCHAR(50) NULL,
  `APELLIDO_MATERNO` VARCHAR(50) NULL,
  `EDAD` INT NOT NULL,
  `CELULAR` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`USUARIO_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `USUARIO_ID_UNIQUE` ON `USUARIO` (`USUARIO_ID` ASC);

SHOW WARNINGS;
CREATE INDEX `NOMBRE_INDEX` ON `USUARIO` (`NOMBRE` ASC, `APELLIDO_PATERNO` ASC, `APELLIDO_MATERNO` ASC);

SHOW WARNINGS;





ALTER TABLE `openpay`.`cuenta` 
ADD INDEX `usuario_id_idx` (`usuario_id` ASC) VISIBLE;
;
ALTER TABLE `openpay`.`cuenta` 
ADD CONSTRAINT `usuario_id`
  FOREIGN KEY (`usuario_id`)
  REFERENCES `openpay`.`usuario` (`USUARIO_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;




ALTER TABLE `openpay`.`credito` 
ADD INDEX `CUENTA_idCUENTA_idx` (`CUENTA_idCUENTA` ASC) VISIBLE;
;
ALTER TABLE `openpay`.`credito` 
ADD CONSTRAINT `CUENTA_idCUENTA`
  FOREIGN KEY (`CUENTA_idCUENTA`)
  REFERENCES `openpay`.`cuenta` (`idCUENTA`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;



ALTER TABLE `openpay`.`cuenta` 
DROP COLUMN `USUARIO_USUARIO_ID`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`idCUENTA`);
;


ALTER TABLE `openpay`.`cuenta` 
DROP FOREIGN KEY `usuario_id`;
ALTER TABLE `openpay`.`cuenta` 
ADD CONSTRAINT `usuario_id`
  FOREIGN KEY (`usuario_id`)
  REFERENCES `openpay`.`usuario` (`USUARIO_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;



  ALTER TABLE `openpay`.`cuenta` 
DROP FOREIGN KEY `usuario_id`;
ALTER TABLE `openpay`.`cuenta` 
ADD CONSTRAINT `usuario_id`
  FOREIGN KEY (`usuario_id`)
  REFERENCES `openpay`.`usuario` (`USUARIO_ID`)
  ON DELETE CASCADE;