spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/openpay?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      testWhileIdle: true
      maxActive: 500
      removeAbandoned: true
      logAbandoned: false
      removeAbandonedTimeout: 60
      maxIdle: 500
      minIdle: 20
      initialSize: 50
      maxWait: 8000
      validationQuery: "SELECT 1 FROM DUAL"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:        
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ConnectionReleaseMode: ON_CLOSE
        store_data_at_delete: true
        format_sql: false
        jdbc: 
          batch_size: 4
        order_inserts: true
        
        
logging:
    level:
        root: INFO        
        mx.oswaldo.openpay: INFO
        org:
            springframework:
                jdbc: INFO
                security: INFO
                web : INFO                   
            hibernate: INFO        
            apache:                
                tomcat:
                    jdbc:
                        pool: INFO
        java:
            sql:
                Connection: INFO
                PreparedStatement: INFO
                Resultset: INFO
                Statement: INFO
                SQLInput: INFO
    file: openpay.log
    pattern:
        file: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger [%file:%line] - %msg%n'
        console: '%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger [%file:%line] - %msg%n'
thread-config:
    corePoolSize: 100
    maxPoolSize: 200
    queueCapacity: 2000
    keepAliveSeconds: 30
    awaitTerminationSeconds: 30
server:
  port: 8080
